image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
- python3
- offpunk
environment:
  site1: ploum.net
  site2: ploum.be
  site3: ploum.eu
tasks:
- publish: |
    mkdir public_html
    mkdir public_gemini
    cd ploum.net
    python3 publish.py
- package-html: |
    cd public_html
    ln -s ../ploum.net/files .
    cp ../ploum.net/files/favicon.ico .
    tar -cvzh . > ../site.tar.gz
- deploy-ploumnet: |
    acurl -f https://pages.sr.ht/publish/$site1 -Fcontent=@site.tar.gz
- deploy-wwwploumnet: |
    acurl -f https://pages.sr.ht/publish/www.$site1 -Fcontent=@site.tar.gz
- deploy-ploumbe: |
    acurl -f https://pages.sr.ht/publish/$site2 -Fcontent=@site.tar.gz
- deploy-wwwploumbe: |
    acurl -f https://pages.sr.ht/publish/www.$site2 -Fcontent=@site.tar.gz
- package-gemini: |
    cd public_gemini
    ln -s ../ploum.net/files .
    tar -cvzh . > ../capsule.tar.gz
- deploy-gemini : |
    acurl -f https://pages.sr.ht/publish/$site1 -Fcontent=@capsule.tar.gz -Fprotocol=GEMINI
    acurl -f https://pages.sr.ht/publish/$site2 -Fcontent=@capsule.tar.gz -Fprotocol=GEMINI
- ping-antenna : |
    offpunk --version
    offpunk --fetch-later gemini://warmedal.se/~antenna/submit?gemini://$site1/index.gmi
    offpunk --sync --assume-yes
- deploy-ploumeu: |
    acurl -f https://pages.sr.ht/publish/$site3 -Fcontent=@site.tar.gz
- deploy-wwwploumeu: |
    acurl -f https://pages.sr.ht/publish/www.$site3 -Fcontent=@site.tar.gz
